server:
  port: 35000
spring:
  application:
    name: nacos-order
  cloud:
    nacos:
      #      server-addr: 127.0.0.1:8848
      server-addr: 192.168.213.130:8848 # nacos集群
      discovery:
        username: nacos
        password: nacos
    loadbalancer:
      ribbon:
        enabled: false  # 该版本的SpringCloud默认是用ribbon进行负载均衡，这里取消使用ribbon，而是使用loadbalance
feign:
  sentinel:
    # openfeign整合sentinel
    enabled: true